# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Luke Cashwell
tagline:          'Me, Myself, and I all welcome you.'
description:      'A personal website containing a specially curated portfolio.'
url:              https://lukecashwell-alt.github.io/eportfolio
baseurl:          https://lukecashwell-alt.github.io/eportfolio/

author:
  name:           'Luke Cashwell'
  url:            https://www.youtube.com/watch?v=dQw4w9WgXcQ

paginate:         5


# Custom vars
version:          3.0

github:
  repo:           https://github.com/lukecashwell-alt/eportfolio/